window.__INIT_DATA__ = {
  "lang": "ru",
  "strings": {
    "app_title": "ZiablWinSetup — Массовая установка софта",
    "app_subtitle": "Быстрая установка софта после переустановки Windows",
    "winget_found": "winget",
    "winget_not_found": "winget не найден",
    "categories": "Категории",
    "cat_all": "Все",
    "cat_browsers": "Браузеры",
    "cat_media": "Медиа",
    "cat_utilities": "Утилиты",
    "cat_communication": "Связь",
    "cat_development": "Разработка",
    "cat_gaming": "Игры и загрузки",
    "cat_vpn_network": "VPN и сеть",
    "cat_gpu_drivers": "GPU и драйверы",
    "cat_office": "Офис и документы",
    "tab_apps": "Приложения",
    "tab_tweaks": "Твики и фичи",
    "tab_metro": "Metro приложения",
    "metro_title": "Встроенные Metro / UWP приложения Windows",
    "metro_subtitle": "Предустановленный системный софт. Удаляйте ненужные встроенные программы и восстанавливайте их в один клик.",
    "metro_status_installed": "Установлено",
    "metro_status_removed": "Удалено",
    "metro_btn_remove": "Удалить",
    "metro_btn_restore": "Восстановить",
    "metro_btn_remove_selected": "Удалить выбранные",
    "metro_btn_restore_selected": "Восстановить выбранные",
    "metro_count_installed": "Установлено: {installed} из {total}",
    "metro_select_all": "Выбрать все",
    "metro_deselect_all": "Снять все",
    "metro_confirm_remove": "Вы действительно хотите удалить выбранные Metro-приложения ({count} шт.)?",
    "btn_check_updates": "Проверить обновления",
    "checking_updates": "Проверка обновлений...",
    "btn_rescan_installed": "Проверить установленное",
    "rescanning_installed": "Проверка установленных программ...",
    "rescan_completed": "Проверка завершена: найдено {count} установленных программ",
    "select_at_least_one": "Выберите хотя бы одно приложение галочкой!",
    "select_at_least_one_update": "Выберите хотя бы одно приложение галочкой для обновления!",
    "no_updates_in_selection": "Среди выбранных приложений нет доступных обновлений.",
    "cat_updates_available": "Требуют обновления",
    "open_web_1progs": "Скачать с 1progs.ru",
    "btn_apply_tweak": "Включить",
    "btn_revert_tweak": "Отключить",
    "btn_clean_action": "Очистить",
    "btn_cleaning": "Очистка...",
    "tweak_applied": "Включено",
    "tweak_not_applied": "Отключено",
    "update_available": "Доступно v{version}",
    "btn_upgrade": "Обновить",
    "btn_upgrade_all": "Обновить все",
    "btn_upgrade_selected": "Обновить выбранные",
    "updates_available_banner": "Доступны обновления для {count} приложений",
    "ignored_update_badge": "Не обновлять авто",
    "ignored_update_tooltip": "Исключено из массового обновления («Обновить все»)",
    "quick_actions": "Быстрые действия",
    "select_recommended": "Рекомендуемые",
    "select_all": "Выбрать все",
    "deselect_all": "Снять все",
    "all_silent": "Все → Тихая",
    "all_interactive": "Все → Интерактивная",
    "mode_interactive": "Интерактивная",
    "mode_silent": "Тихая",
    "btn_download": "Скачать",
    "btn_install": "Установить",
    "btn_install_admin": "Установить (Админ)",
    "btn_reinstall": "Переустановить",
    "btn_uninstall": "Удалить",
    "confirm_uninstall": "Вы действительно хотите запустить деинсталляцию {name}?",
    "btn_extract": "Распаковать",
    "btn_launch": "Запустить",
    "btn_open_folder": "Открыть",
    "btn_download_selected": "Скачать выбранное",
    "btn_install_all": "Установить все скачанные",
    "btn_cancel": "Отменить",
    "status_idle": "Ожидание",
    "status_queued": "В очереди",
    "status_downloading": "Скачивается...",
    "status_downloaded": "Скачано",
    "status_installing": "Установка...",
    "status_installed": "Установлено",
    "status_uninstalling": "Удаление...",
    "status_done": "Готово!",
    "status_error": "Ошибка",
    "status_skipped": "Пропущено",
    "status_extracted": "Распаковано",
    "selected_count": "Выбрано: {count}",
    "downloaded_count": "Скачано: {count}",
    "downloading_progress": "Скачивание: {done}/{total}",
    "installing_progress": "Установка: {done}/{total}",
    "completed": "Завершено",
    "search_placeholder": "Поиск приложения...",
    "log_no_selection": "Не выбрано ни одного приложения!",
    "log_start_download": "Запуск скачивания {count} приложений...",
    "log_downloaded": "{name} — успешно скачано",
    "log_download_error": "{name} — ошибка скачивания: {error}",
    "log_start_install": "Установка: {name}...",
    "log_installed": "{name} — успешно установлено!",
    "log_install_error": "{name} — ошибка установки: {error}",
    "log_start_uninstall": "Деинсталляция: {name}...",
    "log_uninstalled": "{name} — успешно деинсталлировано!",
    "log_uninstall_error": "{name} — ошибка деинсталляции: {error}",
    "log_extracted": "{name} — распаковано в {path}",
    "log_cancelled": "Операция отменена пользователем",
    "log_cancelled_install": "Установка {name} отменена пользователем.",
    "log_cancelled_upgrade": "Обновление {name} отменено пользователем.",
    "log_all_done": "Все операции успешно завершены!",
    "log_download_done": "Загрузка завершена! Нажмите «Установить» на карточках или «Установить все».",
    "settings": "Настройки",
    "extract_path_label": "Путь для распаковки ZIP-архивов:",
    "extract_path_desktop": "Рабочий стол",
    "browse": "Обзор...",
    "language": "Язык / Language",
    "no_admin_warning": "Запущено без прав администратора. Некоторые инсталляторы могут запросить подтверждение UAC.",
    "settings_exclusions": "Исключения автообновления",
    "settings_exclusions_desc": "Выбранные приложения не будут обновляться при нажатии «Обновить все». Вы по-прежнему сможете обновить их вручную.",
    "winget_banner_title": "Windows Package Manager (Winget) не установлен в системе",
    "winget_banner_desc": "Он необходим для быстрой фоновой загрузки и автоматического обновления большинства программ.",
    "btn_install_winget_auto": "⚡ Установить Winget автоматически",
    "btn_open_store": "🛍️ Microsoft Store",
    "winget_installing": "Установка Winget...",
    "winget_install_success": "Winget успешно установлен!"
  },
  "strings_all": {
    "ru": {
      "app_title": "ZiablWinSetup — Массовая установка софта",
      "app_subtitle": "Быстрая установка софта после переустановки Windows",
      "winget_found": "winget",
      "winget_not_found": "winget не найден",
      "categories": "Категории",
      "cat_all": "Все",
      "cat_browsers": "Браузеры",
      "cat_media": "Медиа",
      "cat_utilities": "Утилиты",
      "cat_communication": "Связь",
      "cat_development": "Разработка",
      "cat_gaming": "Игры и загрузки",
      "cat_vpn_network": "VPN и сеть",
      "cat_gpu_drivers": "GPU и драйверы",
      "cat_office": "Офис и документы",
      "tab_apps": "Приложения",
      "tab_tweaks": "Твики и фичи",
      "tab_metro": "Metro приложения",
      "metro_title": "Встроенные Metro / UWP приложения Windows",
      "metro_subtitle": "Предустановленный системный софт. Удаляйте ненужные встроенные программы и восстанавливайте их в один клик.",
      "metro_status_installed": "Установлено",
      "metro_status_removed": "Удалено",
      "metro_btn_remove": "Удалить",
      "metro_btn_restore": "Восстановить",
      "metro_btn_remove_selected": "Удалить выбранные",
      "metro_btn_restore_selected": "Восстановить выбранные",
      "metro_count_installed": "Установлено: {installed} из {total}",
      "metro_select_all": "Выбрать все",
      "metro_deselect_all": "Снять все",
      "metro_confirm_remove": "Вы действительно хотите удалить выбранные Metro-приложения ({count} шт.)?",
      "btn_check_updates": "Проверить обновления",
      "checking_updates": "Проверка обновлений...",
      "btn_rescan_installed": "Проверить установленное",
      "rescanning_installed": "Проверка установленных программ...",
      "rescan_completed": "Проверка завершена: найдено {count} установленных программ",
      "select_at_least_one": "Выберите хотя бы одно приложение галочкой!",
      "select_at_least_one_update": "Выберите хотя бы одно приложение галочкой для обновления!",
      "no_updates_in_selection": "Среди выбранных приложений нет доступных обновлений.",
      "cat_updates_available": "Требуют обновления",
      "open_web_1progs": "Скачать с 1progs.ru",
      "btn_apply_tweak": "Включить",
      "btn_revert_tweak": "Отключить",
      "btn_clean_action": "Очистить",
      "btn_cleaning": "Очистка...",
      "tweak_applied": "Включено",
      "tweak_not_applied": "Отключено",
      "update_available": "Доступно v{version}",
      "btn_upgrade": "Обновить",
      "btn_upgrade_all": "Обновить все",
      "btn_upgrade_selected": "Обновить выбранные",
      "updates_available_banner": "Доступны обновления для {count} приложений",
      "ignored_update_badge": "Не обновлять авто",
      "ignored_update_tooltip": "Исключено из массового обновления («Обновить все»)",
      "quick_actions": "Быстрые действия",
      "select_recommended": "Рекомендуемые",
      "select_all": "Выбрать все",
      "deselect_all": "Снять все",
      "all_silent": "Все → Тихая",
      "all_interactive": "Все → Интерактивная",
      "mode_interactive": "Интерактивная",
      "mode_silent": "Тихая",
      "btn_download": "Скачать",
      "btn_install": "Установить",
      "btn_install_admin": "Установить (Админ)",
      "btn_reinstall": "Переустановить",
      "btn_uninstall": "Удалить",
      "confirm_uninstall": "Вы действительно хотите запустить деинсталляцию {name}?",
      "btn_extract": "Распаковать",
      "btn_launch": "Запустить",
      "btn_open_folder": "Открыть",
      "btn_download_selected": "Скачать выбранное",
      "btn_install_all": "Установить все скачанные",
      "btn_cancel": "Отменить",
      "status_idle": "Ожидание",
      "status_queued": "В очереди",
      "status_downloading": "Скачивается...",
      "status_downloaded": "Скачано",
      "status_installing": "Установка...",
      "status_installed": "Установлено",
      "status_uninstalling": "Удаление...",
      "status_done": "Готово!",
      "status_error": "Ошибка",
      "status_skipped": "Пропущено",
      "status_extracted": "Распаковано",
      "selected_count": "Выбрано: {count}",
      "downloaded_count": "Скачано: {count}",
      "downloading_progress": "Скачивание: {done}/{total}",
      "installing_progress": "Установка: {done}/{total}",
      "completed": "Завершено",
      "search_placeholder": "Поиск приложения...",
      "log_no_selection": "Не выбрано ни одного приложения!",
      "log_start_download": "Запуск скачивания {count} приложений...",
      "log_downloaded": "{name} — успешно скачано",
      "log_download_error": "{name} — ошибка скачивания: {error}",
      "log_start_install": "Установка: {name}...",
      "log_installed": "{name} — успешно установлено!",
      "log_install_error": "{name} — ошибка установки: {error}",
      "log_start_uninstall": "Деинсталляция: {name}...",
      "log_uninstalled": "{name} — успешно деинсталлировано!",
      "log_uninstall_error": "{name} — ошибка деинсталляции: {error}",
      "log_extracted": "{name} — распаковано в {path}",
      "log_cancelled": "Операция отменена пользователем",
      "log_cancelled_install": "Установка {name} отменена пользователем.",
      "log_cancelled_upgrade": "Обновление {name} отменено пользователем.",
      "log_all_done": "Все операции успешно завершены!",
      "log_download_done": "Загрузка завершена! Нажмите «Установить» на карточках или «Установить все».",
      "settings": "Настройки",
      "extract_path_label": "Путь для распаковки ZIP-архивов:",
      "extract_path_desktop": "Рабочий стол",
      "browse": "Обзор...",
      "language": "Язык / Language",
      "no_admin_warning": "Запущено без прав администратора. Некоторые инсталляторы могут запросить подтверждение UAC.",
      "settings_exclusions": "Исключения автообновления",
      "settings_exclusions_desc": "Выбранные приложения не будут обновляться при нажатии «Обновить все». Вы по-прежнему сможете обновить их вручную.",
      "winget_banner_title": "Windows Package Manager (Winget) не установлен в системе",
      "winget_banner_desc": "Он необходим для быстрой фоновой загрузки и автоматического обновления большинства программ.",
      "btn_install_winget_auto": "⚡ Установить Winget автоматически",
      "btn_open_store": "🛍️ Microsoft Store",
      "winget_installing": "Установка Winget...",
      "winget_install_success": "Winget успешно установлен!"
    },
    "en": {
      "app_title": "ZiablWinSetup — Bulk Software Installer",
      "app_subtitle": "Fast batch application setup after fresh Windows install",
      "winget_found": "winget",
      "winget_not_found": "winget not found",
      "categories": "Categories",
      "cat_all": "All",
      "cat_browsers": "Browsers",
      "cat_media": "Media",
      "cat_utilities": "Utilities",
      "cat_communication": "Communication",
      "cat_development": "Development",
      "cat_gaming": "Gaming & Downloads",
      "cat_vpn_network": "VPN & Network",
      "cat_gpu_drivers": "GPU & Drivers",
      "cat_office": "Office & Docs",
      "tab_apps": "Apps",
      "tab_tweaks": "Tweaks & Features",
      "tab_metro": "Metro Apps",
      "metro_title": "Built-in Windows Metro / UWP Apps",
      "metro_subtitle": "Pre-installed system applications. Uninstall unwanted software and restore apps in a single click.",
      "metro_status_installed": "Installed",
      "metro_status_removed": "Uninstalled",
      "metro_btn_remove": "Uninstall",
      "metro_btn_restore": "Restore",
      "metro_btn_remove_selected": "Uninstall Selected",
      "metro_btn_restore_selected": "Restore Selected",
      "metro_count_installed": "Installed: {installed} of {total}",
      "metro_select_all": "Select All",
      "metro_deselect_all": "Deselect All",
      "metro_confirm_remove": "Are you sure you want to remove the selected Metro apps ({count})?",
      "btn_check_updates": "Check for Updates",
      "checking_updates": "Checking updates...",
      "btn_rescan_installed": "Re-scan Installed",
      "rescanning_installed": "Checking installed apps...",
      "rescan_completed": "Scan complete: found {count} installed apps",
      "select_at_least_one": "Please select at least one application with a checkbox!",
      "select_at_least_one_update": "Please select at least one application to update!",
      "no_updates_in_selection": "No updates available among selected applications.",
      "cat_updates_available": "Updates Available",
      "open_web_1progs": "Download from 1progs.ru",
      "btn_apply_tweak": "Enable",
      "btn_revert_tweak": "Disable",
      "btn_clean_action": "Clean",
      "btn_cleaning": "Cleaning...",
      "tweak_applied": "Enabled",
      "tweak_not_applied": "Disabled",
      "update_available": "Update available: v{version}",
      "btn_upgrade": "Upgrade",
      "btn_upgrade_all": "Update All",
      "btn_upgrade_selected": "Update Selected",
      "updates_available_banner": "Updates available for {count} applications",
      "ignored_update_badge": "Skip Auto-Update",
      "ignored_update_tooltip": "Excluded from bulk 'Update All'",
      "quick_actions": "Quick Actions",
      "select_recommended": "Recommended",
      "select_all": "Select All",
      "deselect_all": "Deselect All",
      "all_silent": "All → Silent",
      "all_interactive": "All → Interactive",
      "mode_interactive": "Interactive",
      "mode_silent": "Silent",
      "btn_download": "Download",
      "btn_install": "Install",
      "btn_install_admin": "Install (Admin)",
      "btn_reinstall": "Reinstall",
      "btn_uninstall": "Uninstall",
      "confirm_uninstall": "Are you sure you want to uninstall {name}?",
      "btn_extract": "Extract",
      "btn_launch": "Launch",
      "btn_open_folder": "Open",
      "btn_download_selected": "Download Selected",
      "btn_install_all": "Install All Downloaded",
      "btn_cancel": "Cancel",
      "status_idle": "Idle",
      "status_queued": "Queued",
      "status_downloading": "Downloading...",
      "status_downloaded": "Downloaded",
      "status_installing": "Installing...",
      "status_installed": "Installed",
      "status_uninstalling": "Uninstalling...",
      "status_done": "Done!",
      "status_error": "Error",
      "status_skipped": "Skipped",
      "status_extracted": "Extracted",
      "selected_count": "Selected: {count}",
      "downloaded_count": "Downloaded: {count}",
      "downloading_progress": "Downloading: {done}/{total}",
      "installing_progress": "Installing: {done}/{total}",
      "completed": "Completed",
      "search_placeholder": "Search app...",
      "log_no_selection": "No applications selected!",
      "log_start_download": "Downloading {count} apps...",
      "log_downloaded": "{name} — downloaded",
      "log_download_error": "{name} — error: {error}",
      "log_start_install": "Installing: {name}...",
      "log_installed": "{name} — installed!",
      "log_install_error": "{name} — error: {error}",
      "log_start_uninstall": "Uninstalling: {name}...",
      "log_uninstalled": "{name} — uninstalled!",
      "log_uninstall_error": "{name} — error: {error}",
      "log_extracted": "{name} — extracted to {path}",
      "log_cancelled": "Cancelled by user",
      "log_cancelled_install": "Installation of {name} was cancelled by user.",
      "log_cancelled_upgrade": "Upgrade of {name} was cancelled by user.",
      "log_all_done": "All tasks completed!",
      "log_download_done": "Downloads complete! Click 'Install' on cards or 'Install All'.",
      "settings": "Settings",
      "extract_path_label": "ZIP extraction path:",
      "extract_path_desktop": "Desktop",
      "browse": "Browse...",
      "language": "Language",
      "no_admin_warning": "Running without admin rights. Some installers may request UAC.",
      "settings_exclusions": "Auto-Update Exclusions",
      "settings_exclusions_desc": "Selected apps will not be updated when clicking 'Update All'. You can still update them manually.",
      "winget_banner_title": "Windows Package Manager (Winget) is not installed",
      "winget_banner_desc": "It is required for fast background downloading and automatic updates for most software.",
      "btn_install_winget_auto": "⚡ Install Winget Automatically",
      "btn_open_store": "🛍️ Microsoft Store",
      "winget_installing": "Installing Winget...",
      "winget_install_success": "Winget installed successfully!"
    }
  },
  "apps": [
    {
      "id": "chrome",
      "name": "Google Chrome",
      "description": "Самый популярный веб-браузер в мире от компании Google",
      "description_en": "World's most popular fast, simple, and secure web browser",
      "notes": "",
      "notes_en": "",
      "category": "browsers",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "opera-gx",
      "name": "Opera GX",
      "description": "Геймерский браузер с контролем процессора, ОЗУ и сетевого трафика",
      "description_en": "Gaming browser with CPU, RAM, and network limiters",
      "notes": "",
      "notes_en": "",
      "category": "browsers",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "firefox",
      "name": "Mozilla Firefox",
      "description": "Быстрый браузер с открытым кодом и упором на защиту приватности",
      "description_en": "Fast, private, and independent open-source web browser",
      "notes": "",
      "notes_en": "",
      "category": "browsers",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "brave",
      "name": "Brave Browser",
      "description": "Быстрый приватный браузер со встроенной блокировкой рекламы и трекеров",
      "description_en": "Secure and fast Chromium-based browser with built-in ad blocker",
      "notes": "",
      "notes_en": "",
      "category": "browsers",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "dolphinanty",
      "name": "Dolphin Anty",
      "description": "Антидетект-браузер для мультиаккаунтинга с управлением цифровыми отпечатками",
      "description_en": "Modern anti-detect browser for managing digital browser fingerprints",
      "notes": "",
      "notes_en": "",
      "category": "browsers",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "vlc",
      "name": "VLC Media Player",
      "description": "Универсальный медиаплеер с поддержкой почти всех форматов аудио и видео",
      "description_en": "Free, portable, open-source multi-platform media player and streamer",
      "notes": "",
      "notes_en": "",
      "category": "media",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "klite",
      "name": "K-Lite Codec Pack Full",
      "description": "Набор аудио/видео кодеков с удобным и быстрым плеером MPC-HC",
      "description_en": "Collection of audio/video codecs with lightweight MPC-HC player",
      "notes": "",
      "notes_en": "",
      "category": "media",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "picasa3",
      "name": "Picasa 3",
      "description": "Быстрый классический просмотрщик изображений и фото от Google",
      "description_en": "Classic, ultra-fast photo organizer and viewer by Google",
      "notes": "",
      "notes_en": "",
      "category": "media",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "obs",
      "name": "OBS Studio",
      "description": "Профессиональная программа для видеозаписи экрана и стриминга",
      "description_en": "Free and open source software for video recording and live streaming",
      "notes": "",
      "notes_en": "",
      "category": "media",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "photoshop",
      "name": "Adobe Photoshop",
      "description": "Профессиональный редактор растровой графики и дизайна (активированная версия на 1progs.ru)",
      "description_en": "Industry-standard graphics and photo editing software (via 1progs.ru)",
      "notes": "",
      "notes_en": "",
      "category": "media",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": "https://1progs.ru/adobe-photoshop/"
    },
    {
      "id": "premiere",
      "name": "Adobe Premiere Pro",
      "description": "Профессиональный пакет нелинейного видеомонтажа (активированная версия на 1progs.ru)",
      "description_en": "Professional video editing and post-production suite (via 1progs.ru)",
      "notes": "",
      "notes_en": "",
      "category": "media",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": "https://1progs.ru/adobe-premiere/"
    },
    {
      "id": "7zip",
      "name": "7-Zip",
      "description": "Бесплатный архиватор с высочайшей степенью сжатия форматов 7z, ZIP, RAR",
      "description_en": "Free open-source file archiver with high compression ratio",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "winrar",
      "name": "WinRAR",
      "description": "Популярный архиватор для открытия и создания архивов RAR и ZIP",
      "description_en": "Powerful archive manager supporting RAR, ZIP, and other formats",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "everything",
      "name": "Everything",
      "description": "Молниеносный локальный поиск файлов и папок по именам на NTFS-дисках",
      "description_en": "Ultra-fast filename search engine for Windows NTFS volumes",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "total-commander",
      "name": "Total Commander",
      "description": "Двухпанельный файловый менеджер со встроенным FTP-клиентом и архиватором",
      "description_en": "Feature-rich dual-pane orthodox file manager with FTP client",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "eartrumpet",
      "name": "EarTrumpet",
      "description": "Продвинутый регулятор громкости для Windows с раздельной настройкой для каждого приложения",
      "description_en": "Powerful volume control companion with per-app volume sliders",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "cpuz",
      "name": "CPU-Z",
      "description": "Информация о процессоре, материнской плате, оперативной памяти и таймингах",
      "description_en": "Comprehensive system profiler for CPU, motherboard, and RAM",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "hwinfo",
      "name": "HWiNFO",
      "description": "Глубокая диагностика оборудования, аппаратный мониторинг температур и напряжений",
      "description_en": "Professional hardware analysis, diagnostic, and real-time monitoring",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "sharex",
      "name": "ShareX",
      "description": "Захват экрана, создание скриншотов, запись GIF и мгновенная загрузка в сеть",
      "description_en": "Screen capture, file sharing, and productivity tool with OCR",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "powertoys",
      "name": "Microsoft PowerToys",
      "description": "Набор инструментов Windows для продуктивности: FancyZones, Text Extractor, ColorPicker",
      "description_en": "Set of utilities for power users to tune and streamline Windows",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "crystaldiskinfo",
      "name": "CrystalDiskInfo",
      "description": "Мониторинг состояния и температуры жестких дисков и SSD (S.M.A.R.T.)",
      "description_en": "HDD and SSD health and S.M.A.R.T. monitoring utility",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "crystaldiskmark",
      "name": "CrystalDiskMark",
      "description": "Бенчмарк для измерения скорости чтения и записи накопителей",
      "description_en": "Storage benchmark utility for measuring read/write speeds",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "occt",
      "name": "OCCT Personal",
      "description": "Комплексный стресс-тест стабильности процессора, памяти и блока питания",
      "description_en": "All-in-one CPU, memory, and power supply stability stress test",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "uninstalltool",
      "name": "Uninstall Tool",
      "description": "Чистая деинсталляция программ с глубоким удалением остатков и следов в реестре",
      "description_en": "Powerful uninstaller removing residual files and registry keys",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "unlocker",
      "name": "IObit Unlocker",
      "description": "Быстрая разблокировка и удаление файлов, занятых другими системными процессами",
      "description_en": "Easily unlocks and deletes files locked by system processes",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "unchecker",
      "name": "Unchecky",
      "description": "Автоматическое снятие галочек с рекламных предложений и тулбаров при установке софта",
      "description_en": "Automatically unchecks unwanted software bundles during installations",
      "notes": "",
      "notes_en": "",
      "category": "utilities",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "telegram",
      "name": "Telegram Desktop",
      "description": "Быстрый и безопасный мессенджер с поддержкой каналов и групп",
      "description_en": "Fast and secure desktop messaging app with cloud sync",
      "notes": "",
      "notes_en": "",
      "category": "communication",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "discord",
      "name": "Discord",
      "description": "Голосовой, видео- и текстовый чат для геймеров и сообществ",
      "description_en": "All-in-one voice, video, and text communication platform",
      "notes": "",
      "notes_en": "",
      "category": "communication",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "claude",
      "name": "Claude Desktop",
      "description": "Официальное десктопное приложение ИИ-ассистента Claude от Anthropic",
      "description_en": "Official desktop client for Anthropic's Claude AI assistant",
      "notes": "",
      "notes_en": "",
      "category": "communication",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "chatgpt",
      "name": "ChatGPT Desktop",
      "description": "Официальный клиент ChatGPT для Windows с горячими клавишами и голосовым вводом",
      "description_en": "Official OpenAI ChatGPT Windows client with global hotkey support",
      "notes": "",
      "notes_en": "",
      "category": "communication",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "todoist",
      "name": "Todoist",
      "description": "Популярный планировщик задач, списков дел и проектов",
      "description_en": "Organize your work and personal life with task manager",
      "notes": "",
      "notes_en": "",
      "category": "communication",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "vscode",
      "name": "Visual Studio Code",
      "description": "Мощный легковесный редактор кода от Microsoft с огромной экосистемой расширений",
      "description_en": "Streamlined lightweight code editor with vast extensions library",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "pycharm",
      "name": "PyCharm Community",
      "description": "Интеллектуальная среда разработки Python от JetBrains с умной подсветкой и отладчиком",
      "description_en": "Intelligent Python IDE by JetBrains with code analysis",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "sublimetext",
      "name": "Sublime Text",
      "description": "Сверхбыстрый и отзывчивый редактор кода и заметок",
      "description_en": "Sophisticated text editor for code, markup, and prose",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "notepadpp",
      "name": "Notepad++",
      "description": "Быстрый текстовый редактор с подсветкой синтаксиса и вкладками",
      "description_en": "Free and fast source code and text editor replacing Notepad",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "git",
      "name": "Git",
      "description": "Распределённая система контроля версий для отслеживания изменений в коде",
      "description_en": "Fast, scalable, distributed revision control system",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "python",
      "name": "Python 3",
      "description": "Современный язык программирования общего назначения для скриптов и разработки",
      "description_en": "High-level scripting and programming language with pip and venv",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "java",
      "name": "Java (Eclipse Temurin JDK 21)",
      "description": "Среда исполнения и компиляции Java от сообщества Adoptium (LTS-релиз)",
      "description_en": "High-performance, cross-platform enterprise Java runtime (LTS)",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": false,
      "installer_type": "msi",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "codex",
      "name": "OpenAI Codex CLI",
      "description": "Консольный инструмент и агент кодинга на базе моделей OpenAI",
      "description_en": "Command-line AI coding assistant and agent",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "opencode",
      "name": "OpenCode AI",
      "description": "Открытая платформа и среда разработки с поддержкой ИИ",
      "description_en": "Open-source AI-assisted coding environment",
      "notes": "",
      "notes_en": "",
      "category": "development",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "nvidia-app",
      "name": "NVIDIA App (GeForce Experience)",
      "description": "Центр управления графикой, обновление драйверов и оптимизация игр NVIDIA",
      "description_en": "Official client for NVIDIA GPU driver updates and game tuning",
      "notes": "Для видеокарт NVIDIA GeForce",
      "notes_en": "For NVIDIA GeForce graphics cards",
      "category": "gpu_drivers",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "amd-software",
      "name": "AMD Software: Adrenalin Edition",
      "description": "Панель управления и драйверы для видеокарт AMD Radeon",
      "description_en": "Drivers and software control panel for AMD Radeon GPUs",
      "notes": "Для видеокарт AMD Radeon",
      "notes_en": "For AMD Radeon graphics cards",
      "category": "gpu_drivers",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "gpuz",
      "name": "TechPowerUp GPU-Z",
      "description": "Подробные характеристики видеокарты, частот, видеопамяти и датчиков",
      "description_en": "Lightweight utility providing detailed information on video cards and GPU",
      "notes": "Портативная утилита, не требует установки",
      "notes_en": "Portable standalone utility, runs without installation",
      "category": "gpu_drivers",
      "recommended": true,
      "installer_type": "portable",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "furmark",
      "name": "Geeks3D FurMark 2",
      "description": "Интенсивный стресс-тест видеокарты и бенчмарк стабильности («бублик»)",
      "description_en": "Intensive GPU stress test and stability benchmark",
      "notes": "",
      "notes_en": "",
      "category": "gpu_drivers",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "driverbooster",
      "name": "IObit Driver Booster",
      "description": "Автоматическое сканирование и обновление устаревших драйверов Windows (активированная версия на 1progs.ru)",
      "description_en": "Automatic scanning and updating for outdated device drivers (Pro via 1progs.ru)",
      "notes": "",
      "notes_en": "",
      "category": "gpu_drivers",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": "https://1progs.ru/iobit-driver-booster-pro/"
    },
    {
      "id": "amnezia-vpn",
      "name": "AmneziaVPN",
      "description": "Бесплатный VPN-клиент с поддержкой устойчивых протоколов",
      "description_en": "Free open-source VPN client supporting modern protocols",
      "notes": "",
      "notes_en": "",
      "category": "vpn_network",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "zapret",
      "name": "Zapret (Discord/YouTube разблокировка)",
      "description": "Обход замедлений и блокировок Discord и YouTube без VPN",
      "description_en": "Bypass throttling and blocking of Discord & YouTube without VPN",
      "notes": "Распакуется на Рабочий стол с готовым ярлыком для запуска",
      "notes_en": "Extracts to Desktop with an auto-created launch shortcut",
      "category": "vpn_network",
      "recommended": true,
      "installer_type": "zip",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "yogadns",
      "name": "YogaDNS",
      "description": "Продвинутый системный DNS-клиент с поддержкой DoH, DoT и правил маршрутизации",
      "description_en": "Advanced DNS client supporting DNS-over-HTTPS, DoT, and rule routing",
      "notes": "",
      "notes_en": "",
      "category": "vpn_network",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "tgwsproxy",
      "name": "Tg-WS Proxy (Flowseal)",
      "description": "Локальный MTProto WebSocket прокси для обхода блокировок и замедления Telegram",
      "description_en": "Local MTProto WebSocket bridge proxy to accelerate Telegram connections",
      "notes": "Портативная консольная утилита",
      "notes_en": "Portable standalone CLI utility",
      "category": "vpn_network",
      "recommended": true,
      "installer_type": "portable",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "operaproxy",
      "name": "Opera Proxy (Alexey71)",
      "description": "Автономный прокси-клиент для подключения к серверам Opera VPN без браузера",
      "description_en": "Standalone proxy client for connecting to Opera VPN servers",
      "notes": "Портативная консольная утилита",
      "notes_en": "Portable standalone CLI utility",
      "category": "vpn_network",
      "recommended": false,
      "installer_type": "portable",
      "has_silent": false,
      "web_url": null
    },
    {
      "id": "anydesk",
      "name": "AnyDesk",
      "description": "Быстрое и защищённое подключение к удалённому рабочему столу",
      "description_en": "Fast and lightweight remote desktop connection software",
      "notes": "",
      "notes_en": "",
      "category": "vpn_network",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "steam",
      "name": "Steam",
      "description": "Крупнейшая платформа цифровой дистрибуции игр от Valve",
      "description_en": "Ultimate online game store and community platform by Valve",
      "notes": "",
      "notes_en": "",
      "category": "gaming",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "qbittorrent",
      "name": "qBittorrent",
      "description": "Бесплатный торрент-клиент с чистым интерфейсом без рекламы",
      "description_en": "Free and reliable open-source torrent client without ads",
      "notes": "",
      "notes_en": "",
      "category": "gaming",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "bittorrent",
      "name": "BitTorrent",
      "description": "Классический торрент-клиент для скачивания больших файлов",
      "description_en": "Classic peer-to-peer file sharing and torrent client",
      "notes": "",
      "notes_en": "",
      "category": "gaming",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "dropbox",
      "name": "Dropbox",
      "description": "Надёжное облачное хранилище и синхронизация документов",
      "description_en": "Reliable cloud storage, file backup and syncing service",
      "notes": "",
      "notes_en": "",
      "category": "gaming",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "obsidian",
      "name": "Obsidian",
      "description": "База знаний и заметочник на основе локальных файлов Markdown",
      "description_en": "Extensible note-taking and personal knowledge base on Markdown",
      "notes": "",
      "notes_en": "",
      "category": "office",
      "recommended": true,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "libreoffice",
      "name": "LibreOffice",
      "description": "Полноценный бесплатный офисный пакет для документов и таблиц",
      "description_en": "Free and powerful open source office suite",
      "notes": "",
      "notes_en": "",
      "category": "office",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    },
    {
      "id": "openoffice",
      "name": "Apache OpenOffice",
      "description": "Классический офисный пакет с открытым исходным кодом",
      "description_en": "Classic open-source productivity suite",
      "notes": "",
      "notes_en": "",
      "category": "office",
      "recommended": false,
      "installer_type": "exe",
      "has_silent": true,
      "web_url": null
    }
  ],
  "categories": [
    {
      "id": "all",
      "name": "Все",
      "name_ru": "Все",
      "name_en": "All",
      "count": 58
    },
    {
      "id": "browsers",
      "name": "Браузеры",
      "name_ru": "Браузеры",
      "name_en": "Browsers",
      "count": 5
    },
    {
      "id": "media",
      "name": "Медиа",
      "name_ru": "Медиа",
      "name_en": "Media",
      "count": 6
    },
    {
      "id": "utilities",
      "name": "Утилиты",
      "name_ru": "Утилиты",
      "name_en": "Utilities",
      "count": 15
    },
    {
      "id": "communication",
      "name": "Связь",
      "name_ru": "Связь",
      "name_en": "Communication",
      "count": 5
    },
    {
      "id": "development",
      "name": "Разработка",
      "name_ru": "Разработка",
      "name_en": "Development",
      "count": 9
    },
    {
      "id": "gpu_drivers",
      "name": "GPU и драйверы",
      "name_ru": "GPU и драйверы",
      "name_en": "GPU & Drivers",
      "count": 5
    },
    {
      "id": "vpn_network",
      "name": "VPN и сеть",
      "name_ru": "VPN и сеть",
      "name_en": "VPN & Network",
      "count": 6
    },
    {
      "id": "gaming",
      "name": "Игры и загрузки",
      "name_ru": "Игры и загрузки",
      "name_en": "Gaming & Downloads",
      "count": 4
    },
    {
      "id": "office",
      "name": "Офис и документы",
      "name_ru": "Офис и документы",
      "name_en": "Office & Docs",
      "count": 3
    }
  ],
  "recommended": [
    "chrome",
    "firefox",
    "brave",
    "vlc",
    "obs",
    "7zip",
    "everything",
    "eartrumpet",
    "cpuz",
    "sharex",
    "powertoys",
    "crystaldiskinfo",
    "crystaldiskmark",
    "uninstalltool",
    "unchecker",
    "telegram",
    "discord",
    "claude",
    "chatgpt",
    "vscode",
    "pycharm",
    "notepadpp",
    "git",
    "python",
    "gpuz",
    "zapret",
    "tgwsproxy",
    "steam",
    "qbittorrent",
    "obsidian"
  ],
  "installed_apps": {},
  "tweaks": [
    {
      "id": "torrent_ads",
      "name": "Отключение рекламы в BitTorrent и uTorrent",
      "description": "Полностью выключает рекламные баннеры, всплывающие видео и спонсорские блоки в интерфейсе торрент-клиента без сторонних программ.",
      "category": "apps",
      "icon": "🚫",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "win11_classic_menu",
      "name": "Классическое контекстное меню Windows 11",
      "description": "Возвращает полноценное меню по правому клику мыши без необходимости нажимать «Показать дополнительные параметры».",
      "category": "system",
      "icon": "🪟",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "taskbar_align_left",
      "name": "Кнопка «Пуск» слева (как в Windows 10)",
      "description": "Перемещает кнопку «Пуск» и значки панели задач в левый угол, возвращая привычный классический вид Windows 10.",
      "category": "system",
      "icon": "📌",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "hide_taskbar_search",
      "name": "Скрыть строку поиска на панели задач",
      "description": "Убирает громоздкое поле поиска с панели задач, освобождая полезное место для открытых окон и программ.",
      "category": "system",
      "icon": "🔍",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "disable_indexing_ssd",
      "name": "Отключение службы индексации (для SSD)",
      "description": "Отключает постоянное фоновое чтение и запись индексатора Windows Search. Продлевает ресурс ячеек SSD (TBW) и снижает нагрузку на CPU.",
      "category": "perf",
      "icon": "⚡",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "show_file_ext",
      "name": "Отображение расширений файлов",
      "description": "Показывает реальные расширения файлов (.exe, .bat, .zip) в Проводнике Windows для безопасности и защиты от вирусов.",
      "category": "system",
      "icon": "📁",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "ultimate_perf",
      "name": "Схема «Максимальная производительность»",
      "description": "Активирует скрытую схему питания от Microsoft, отключающую задержки троттлинга процессора для максимального отклика в играх.",
      "category": "perf",
      "icon": "🚀",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "disable_start_ads",
      "name": "Отключение рекламы в меню «Пуск»",
      "description": "Отключает рекламу приложений, навязчивые предложения и подсказки в меню «Пуск» Windows 10/11.",
      "category": "system",
      "icon": "🔇",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "toggle"
    },
    {
      "id": "clean_steam_cache",
      "name": "Очистить кэш загрузок и шейдеров Steam",
      "description": "Устраняет зависания при обновлении и запуске игр в Steam, очищает временный htmlcache, шейдеры и освобождает гигабайты памяти.",
      "category": "cleanup",
      "icon": "🎮",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "action"
    },
    {
      "id": "clean_telegram_cache",
      "name": "Очистить медиа-кэш Telegram Desktop",
      "description": "Очищает все временные фото, видео, стикеры и кэш встроенных ботов/мини-аппов во всех аккаунтах. Все данные остаются в облаке Telegram.",
      "category": "cleanup",
      "icon": "💬",
      "applied": false,
      "available": true,
      "unavailable_reason": "",
      "type": "action"
    }
  ],
  "metro_apps": [
    {
      "id": "weather",
      "name": "MSN Погода",
      "description": "Прогноз погоды, карты осадков и виджеты от Microsoft.",
      "icon": "🌤️",
      "store_id": "9WZDNCRFJ3Q2",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "news",
      "name": "Microsoft Новости",
      "description": "Новостная лента MSN и встроенный контент виджетов Windows.",
      "icon": "📰",
      "store_id": "9WZDNCRFHVFW",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "camera",
      "name": "Камера Windows",
      "description": "Стандартное UWP-приложение для веб-камеры и съемки фото/видео.",
      "icon": "📷",
      "store_id": "9WZDNCRFJBBG",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "maps",
      "name": "Карты Windows",
      "description": "Встроенные оффлайн-карты, навигация и геолокация от Microsoft.",
      "icon": "🗺️",
      "store_id": "9WZDNCRBXB69",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "sound_recorder",
      "name": "Запись голоса (Диктофон)",
      "description": "Базовое приложение записи звука и заметок с микрофона.",
      "icon": "🎙️",
      "store_id": "9WZDNCRFHWKN",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "phone_link",
      "name": "Связь с телефоном (Phone Link)",
      "description": "Синхронизация звонков, SMS и уведомлений со смартфона Android/iOS.",
      "icon": "📱",
      "store_id": "9NBLGGH4VST9",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "feedback_hub",
      "name": "Центр отзывов (Feedback Hub)",
      "description": "Отправка диагностических отчетов и предложений в Microsoft.",
      "icon": "💬",
      "store_id": "9NBLGGH4R32N",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "get_help",
      "name": "Техническая поддержка (Get Help)",
      "description": "Справка и виртуальный агент службы поддержки Microsoft.",
      "icon": "❓",
      "store_id": "9PKDZBMV1H3T",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "tips",
      "name": "Советы Windows (Tips)",
      "description": "Обучающие подсказки и руководство по функциям Windows.",
      "icon": "💡",
      "store_id": "9WZDNCRFJBDG",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "solitaire",
      "name": "Пасьянсы (Solitaire Collection)",
      "description": "Предустановленная карточная игра (Косынка, Паук, Солитер) со встроенной рекламой.",
      "icon": "🃏",
      "store_id": "9WZDNCRFHWD2",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "zune_video",
      "name": "Кино и ТВ (Movies & TV)",
      "description": "Встроенный UWP-плеер видеофайлов и магазин фильмов.",
      "icon": "🎬",
      "store_id": "9WZDNCRFJ3P2",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "zune_music",
      "name": "Windows Медиаплеер (Groove)",
      "description": "Стандартный музыкальный проигрыватель Windows 11.",
      "icon": "🎵",
      "store_id": "9WZDNCRFJ3PT",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "xbox_overlay",
      "name": "Xbox Game Bar",
      "description": "Игровой оверлей Windows (Win+G): запись экрана, виджеты и мониторинг FPS.",
      "icon": "🎮",
      "store_id": "9NZKPSTSNW4P",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "xbox_app",
      "name": "Приложение Xbox",
      "description": "Клиент сервиса Xbox Game Pass и облачных игр.",
      "icon": "🎯",
      "store_id": "9MV0B5HZVK9Z",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "cortana",
      "name": "Cortana (Кортана)",
      "description": "Устаревший голосовой ассистент от Microsoft.",
      "icon": "⭕",
      "store_id": "9NBLGGH4NS1M",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "paint_3d",
      "name": "Paint 3D",
      "description": "Редактор трехмерных моделей и графики.",
      "icon": "🧊",
      "store_id": "9NBLGGH5FV99",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "sticky_notes",
      "name": "Записки (Sticky Notes)",
      "description": "Быстрые цветные стикеры-заметки на Рабочем столе.",
      "icon": "📝",
      "store_id": "9NBLGGH4QGHW",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "alarms",
      "name": "Часы и будильники",
      "description": "Таймеры, секундомер, будильники и мировое время.",
      "icon": "⏰",
      "store_id": "9WZDNCRFJ3PR",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "calculator",
      "name": "Калькулятор Windows",
      "description": "Встроенный калькулятор с инженерным режимом и конвертером валют.",
      "icon": "🔢",
      "store_id": "9WZDNCRFHVN5",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "clipchamp",
      "name": "Clipchamp (Видеоредактор)",
      "description": "Встроенный в Windows 11 онлайн/UWP редактор видеоклипов.",
      "icon": "✂️",
      "store_id": "9P1J8S7CCWWT",
      "can_remove": true,
      "installed": false
    },
    {
      "id": "people",
      "name": "Люди (Контакты)",
      "description": "Интеграция адресной книги и контактов Windows.",
      "icon": "👥",
      "store_id": "9NBLGGH10PG8",
      "can_remove": true,
      "installed": false
    }
  ],
  "ignored_updates": [
    "photoshop",
    "premiere",
    "uninstalltool"
  ],
  "system_info": {
    "winget_available": true,
    "winget_version": "",
    "is_admin": false,
    "extract_path": ""
  }
};
window.INIT_DATA = window.__INIT_DATA__;
window.PRELOAD_DATA = window.__INIT_DATA__;
